// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./components/AppButton.vue')['default'];
    HelloWorld: typeof import('./components/HelloWorld.vue')['default'];
    LocaleSwitcher: typeof import('./components/LocaleSwitcher.vue')['default'];
    SvgIcon: typeof import('./components/SvgIcon.vue')['default'];
  }
}

export {};
